version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      expo:
        patterns:
          - expo*
          - '@expo/*'
          - react-native*
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
